# 深度图带参考图
GENERATE_DEPTH_MAP_WITH_REFERENCE = (
    "You are receiving a DEPTH MAP image:\n\n"
    "DEPTH MAP:\n"
    "- Black and white gradient representing depth\n"
    "- White = closest objects, Black = farthest objects\n"
    "- Shows spatial relationships and 3D structure\n\n"
    "YOUR TASK:\n"
    "1. Interpret the depth map to understand scene geometry\n"
    "2. Generate photorealistic 3D render based on this structure\n"
    "3. Choose appropriate materials, colors, and lighting\n\n"
    "USER PROMPT (THE SUPREME COMMAND):\n"
    "- The User Prompt below is your PRIMARY INSTRUCTION.\n"
    "- You MUST follow the user's description for materials, colors, and lighting.\n"
    "- The Depth Map provides the SHAPE, the User Prompt provides the LOOK.\n"
)

# 深度图不带参考
GENERATE_DEPTH_MAP_WITHOUT_REFERENCE = (
    "You are receiving TWO images with different purposes:\n\n"
    "IMAGE 1 (Style Reference):\n"
    "- Use ONLY for: color palette, material textures, lighting mood, surface details\n"
    "- DO NOT copy: composition, object placement, camera angle\n"
    "- Extract: visual aesthetics, aspect ratio\n\n"
    "IMAGE 2 (Depth Map):\n"
    "- Black and white gradient representing depth\n"
    "- White = closest objects, Black = farthest objects\n"
    "- Use for: scene composition, object placement, 3D structure\n"
    "- This depth map shows the spatial layout\n\n"
    "YOUR TASK:\n"
    "1. Understand 3D scene structure from depth map (IMAGE 2)\n"
    "2. Apply visual style from reference (IMAGE 1) to that structure\n"
    "3. Create photorealistic render combining: reference style + depth map geometry\n"
    "4. Match aspect ratio of reference image\n\n"
    "USER PROMPT (THE SUPREME COMMAND):\n"
    "- The User Prompt below OVERRIDES everything else for CONTENT decisions.\n"
    "- If user says 'make it red', MAKE IT RED, even if Reference is blue.\n"
    "- Reference Image is for STYLE only. User Prompt is for CONTENT.\n"
    "- CONFLICT RESOLUTION: User Prompt > Reference Image Style > Depth Map\n"
)

# 生成渲染图带参考图
GENERATE_RENDER_WITH_REFERENCE = (
    "You are receiving TWO images:\n\n"
    "IMAGE 1 (3D Render - YOUR STRUCTURE SOURCE):\n"
    "- This is the GEOMETRY and LAYOUT you must preserve\n"
    "- Use this EXCLUSIVELY for object positions and composition\n"
    "- IGNORE its bad materials and lighting\n"
    "- This defines WHAT is in the scene\n\n"
    "IMAGE 2 (Style Reference - YOUR VISUAL GUIDE):\n"
    "- This is the STYLE source (materials, lighting, colors)\n"
    "- DO NOT copy objects from here, only their 'look'\n"
    "- Apply this style to the geometry of IMAGE 1\n"
    "- This defines HOW the scene looks\n\n"
    "USER PROMPT (THE SUPREME COMMAND):\n"
    "- The User Prompt below OVERRIDES everything else for CONTENT decisions.\n"
    "- If user says 'black background', MAKE IT BLACK, even if Reference Image has a detailed background.\n"
    "- If user says 'add neon lights', ADD THEM, even if Reference Image is dark.\n"
    "- Reference Image is for STYLE (how things look), User Prompt is for CONTENT (what things are).\n"
    "- CONFLICT RESOLUTION: User Prompt > Reference Image Style > Input Render\n\n"
    "YOUR TASK - AGGRESSIVE TRANSFORMATION:\n"
    "1. Keep ONLY the composition/layout from IMAGE 1 (Depth/Structure)\n"
    "2. COMPLETELY REPLACE materials, lighting, colors with IMAGE 2's style (UNLESS User Prompt says otherwise)\n"
    "3. Make materials look like IMAGE 2 (if metallic there → metallic here)\n"
    "4. Match IMAGE 2's lighting direction, intensity, and color temperature\n"
    "5. Use IMAGE 2's color palette - forget IMAGE 1's colors\n"
    "6. Replicate IMAGE 2's atmosphere, depth, and mood\n"
    "7. Think: 'IMAGE 1 is the skeleton, IMAGE 2 is the skin'\n\n"
    "CRITICAL - DON'T BE CONSERVATIVE:\n"
    "- If IMAGE 1 is blue but IMAGE 2 is warm → make it WARM\n"
    "- If IMAGE 1 is flat but IMAGE 2 has depth → add DEPTH\n"
    "- If IMAGE 1 is simple but IMAGE 2 is detailed → add DETAILS\n"
    "- TRANSFORM aggressively, don't just 'improve' IMAGE 1\n"
    "- STRICTLY FOLLOW IMAGE 1's GEOMETRY/LAYOUT. Do not add objects from IMAGE 2.\n"
)

# 生成渲染图不带参考图
GENERATE_RENDER_WITHOUT_REFERENCE = (
    "You are receiving a LOW-QUALITY 3D RENDER that needs COMPLETE VISUAL OVERHAUL:\n\n"
    "INPUT IMAGE (ROUGH DRAFT ONLY):\n"
    "- Amateur 3D render with placeholder materials and basic lighting\n"
    "- Use ONLY for general composition and object positions\n"
    "- Colors are WRONG, materials are FAKE, lighting is FLAT\n"
    "- This is NOT the target quality - you must COMPLETELY rebuild it\n\n"
    "YOUR MISSION - TOTAL TRANSFORMATION:\n"
    "1. REPLACE all materials with photorealistic equivalents:\n"
    "   - Metal → realistic metal with proper reflections, anisotropy, scratches\n"
    "   - Plastic → varied surface finish, subtle color variation, wear\n"
    "   - Wood → visible grain, natural color variation, texture depth\n"
    "   - Glass → proper refraction, reflections, subtle imperfections\n"
    "   - Fabric → weave patterns, soft shadows, natural draping\n\n"
    "2. REBUILD lighting from scratch:\n"
    "   - Add professional 3-point lighting or natural light sources\n"
    "   - Strong shadows with soft edges\n"
    "   - Realistic reflections and bounce light\n"
    "   - Ambient occlusion in corners and crevices\n"
    "   - Color temperature variation (warm/cool balance)\n\n"
    "3. REIMAGINE colors:\n"
    "   - Input colors are just suggestions - make them BETTER\n"
    "   - Add professional color grading\n"
    "   - Harmonious palette with contrast\n"
    "   - Natural color variation within surfaces\n\n"
    "4. ADD depth and atmosphere:\n"
    "   - Volumetric lighting effects (god rays, haze)\n"
    "   - Atmospheric perspective (depth fog)\n"
    "   - Particle effects if appropriate (dust, moisture)\n"
    "   - Background depth and detail\n\n"
    "5. ENHANCE with imperfections:\n"
    "   - Surface scratches, dents, wear patterns\n"
    "   - Fingerprints on smooth surfaces\n"
    "   - Dust accumulation in corners\n"
    "   - Natural aging and weathering\n\n"
    "USER PROMPT (THE SUPREME COMMAND):\n"
    "- The User Prompt below is your PRIMARY INSTRUCTION for the transformation.\n"
    "- If user says 'make it cyberpunk', use cyberpunk materials/lighting.\n"
    "- If user says 'add rain', add rain.\n"
    "- The input render provides the COMPOSITION, the User Prompt provides the STYLE/CONTENT.\n\n"
    "CRITICAL MINDSET:\n"
    "- Think: 'This is a SKETCH, not the final image'\n"
    "- Your goal: 'Student work' → 'Professional portfolio piece'\n"
    "- Be BOLD with changes - the input is intentionally low quality\n"
    "- Don't preserve bad materials or flat lighting\n"
    "- Make every surface, light, and color DRAMATICALLY better\n"
    "- Aim for: movie VFX quality or high-end product photography\n"
)

# -------------------------------- 编辑图片 --------------------------------

# 智能修复
EDIT_SMART_REPAIR = (
    "COMPOSITE FINALIZATION - Unify entire image into seamless photorealistic result:\n\n"
    "CRITICAL CONTEXT:\n"
    "This image was created through multiple compositing steps (adding objects, inpainting, etc.).\n"
    "Your task: Make it look like ONE UNIFIED PHOTOGRAPH, not a collage.\n"
    "Remove ALL visible seams, color mismatches, lighting inconsistencies.\n\n"
    "COMMON PROBLEMS TO FIX:\n"
    "1. Objects have different color temperatures (some warm, some cool)\n"
    "2. Brightness mismatches between added objects and original scene\n"
    "3. Contrast differences (some areas too contrasty, others too flat)\n"
    "4. Shadow inconsistencies (direction or hardness doesn't match)\n"
    "5. Visible compositing edges or halos around objects\n"
    "6. Objects don't feel grounded in the scene\n"
    "7. Overall image lacks cohesion - looks like separate pieces\n\n"
    "YOUR TASK - PROFESSIONAL COLOR GRADING & UNIFICATION:\n"
    "STEP 1 - ANALYZE ENTIRE COMPOSITION:\n"
    "- Identify which areas look 'off' or disconnected\n"
    "- Find color temperature conflicts\n"
    "- Detect brightness/contrast mismatches\n"
    "- Look for unnatural edges or transitions\n\n"
    "STEP 2 - UNIFIED LIGHTING:\n"
    "- Establish ONE dominant light direction for entire scene\n"
    "- Make ALL objects respect this light direction\n"
    "- Unify shadow hardness across all elements\n"
    "- Add missing ambient occlusion between objects\n"
    "- Strengthen contact shadows where objects meet surfaces\n\n"
    "STEP 3 - COLOR HARMONY:\n"
    "- Choose ONE color temperature for the entire scene\n"
    "- Grade ALL objects to match this temperature\n"
    "- Create unified color palette - no outliers\n"
    "- Add subtle color spill between neighboring elements\n"
    "- Match saturation levels across all objects\n\n"
    "STEP 4 - CONTRAST & EXPOSURE:\n"
    "- Unify exposure - no objects too bright or too dark\n"
    "- Match contrast levels between all elements\n"
    "- Balance highlights and shadows across scene\n"
    "- Create cohesive tonal range\n\n"
    "STEP 5 - SEAMLESS INTEGRATION:\n"
    "- Blend ALL visible compositing edges\n"
    "- Remove halos, color fringing, or artifacts\n"
    "- Add atmospheric perspective if needed (distant = hazier)\n"
    "- Unify sharpness/blur across scene\n"
    "- Add subtle film grain or noise uniformly\n\n"
    "STEP 6 - GROUNDING & REALISM:\n"
    "- Ensure all objects cast appropriate shadows\n"
    "- Add reflections where needed (floors, mirrors, glossy surfaces)\n"
    "- Create subtle light bounce between objects\n"
    "- Add depth cues (foreground sharper, background softer)\n"
    "- Make everything feel 'heavy' and physically present\n\n"
    "REAL-WORLD EXAMPLE:\n"
    "BEFORE: Room with added furniture - chair too warm, table too bright, \n"
    "        plant has harsh shadows while room has soft shadows, visible edge around lamp\n"
    "AFTER FINALIZATION:\n"
    "  → ALL objects color-graded to match room's cool daylight\n"
    "  → Chair brightness reduced to match room exposure\n"
    "  → ALL shadows softened to match ambient lighting\n"
    "  → Lamp edge blended perfectly\n"
    "  → Added contact shadows under all furniture\n"
    "  → Slight color spill from wooden floor onto chair legs\n"
    "  → Unified film grain over entire image\n"
    "  → Result: Looks like ONE photograph, not composite\n\n"
    "CRITICAL SUCCESS CRITERIA:\n"
    "✅ Image looks like ONE unified photograph\n"
    "✅ ALL objects respect same lighting direction\n"
    "✅ Consistent color temperature throughout\n"
    "✅ Matched contrast and exposure across all elements\n"
    "✅ NO visible compositing edges or seams\n"
    "✅ Shadows are consistent (direction, hardness, color)\n"
    "✅ Every object feels grounded and physically present\n"
    "✅ Overall color harmony - no jarring mismatches\n"
    "✅ Professional photorealistic result\n"
    "CRITICAL RULES:\n"
    "❌ NEVER leave color temperature conflicts\n"
    "❌ NEVER ignore exposure mismatches\n"
    "❌ NEVER skip shadow unification\n"
    "❌ NEVER leave visible compositing edges\n"
    "❌ NEVER keep objects that look 'pasted on'\n"
    "❌ NEVER leave lighting direction conflicts\n\n"
    "REMEMBER:\n"
    "You are a PROFESSIONAL COLORIST doing final grade.\n"
    "This is the LAST STEP before client delivery.\n"
    "Make it PERFECT - unified, seamless, photorealistic.\n"
    "Goal: Viewer should NEVER suspect this was composited.\n"
)
# 编辑-带遮罩及参考图
EDIT_WITH_MASK_AND_REFERENCES = (
    "🎯 CRITICAL: READ USER'S PROMPT FIRST!\n"
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    f"USER'S INSTRUCTION (DO THIS EXACTLY!):\n"
    f'"%s"\n'
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
    "YOUR TASK - SIMPLE AND DIRECT:\n"
    "1. Read user's prompt above - THIS IS WHAT YOU MUST DO!\n"
    "2. Look at IMAGE 1 (scene with sketch) - ERASE the sketch\n"
    "3. Look at IMAGE 2 (mask - colored area) - this is WHERE to place it\n"
    "4. Look at IMAGE OTHER (reference) - find the object user wants\n"
    "5. Place object from IMAGE OTHER into the colored area from IMAGE 1\n"
    "6. Follow user's prompt for HOW to place it (sitting/standing/facing/etc)\n"
    "7. Relight object to match scene lighting\n\n"
    "WHAT YOU HAVE:\n"
    "• IMAGE 1 (SCENE) = Where to add it (has colored sketch showing location)\n"
    "• IMAGE 2 (MASK) = Exact colored area for placement\n"
    "• IMAGES OTHER (REFERENCE) = The object user wants to add\n"
    "• USER PROMPT = Tells you WHAT and HOW\n\n"
    "CRITICAL RULES:\n"
    " RULE #1: USER'S PROMPT IS LAW - Follow it EXACTLY!\n"
    " RULE #2: Place object in colored area from IMAGE 2 (mask)\n"
    " RULE #3: ERASE sketch completely - replace with real object\n"
    " RULE #4: Relight object to match IMAGE 1 lighting\n\n"
    "SIMPLE EXAMPLE:\n"
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    "USER PROMPT: 'добавь мужчину на траве в обведённом кругу'\n"
    "\n"
    "WHAT YOU DO:\n"
    "1. Look at IMAGE 1 → find the man\n"
    "2. Look at IMAGE 3 → see the colored circle on grass\n"
    "3. Look at IMAGE 2 → see the sketch circle (erase it!)\n"
    "4. Place man from IMAGE 1 into circle area\n"
    "5. Make him ON THE GRASS (user said 'на траве')\n"
    "6. Erase colored circle sketch\n"
    "7. Relight man to match outdoor lighting\n"
    "8. Cast shadow on grass\n"
    "9. DONE - man is now on grass in that spot!\n"
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
    "HOW TO DO IT:\n"
    "STEP 1 - READ USER PROMPT (at the top!):\n"
    "  → What object? (e.g., 'мужчину', 'chair', 'car')\n"
    "  → Where? (e.g., 'на траве', 'at desk', 'in corner')\n"
    "  → How? (e.g., 'standing', 'sitting', 'facing camera')\n\n"
    "STEP 2 - FIND OBJECT IN IMAGE 1:\n"
    "  → Identify the object user wants\n"
    "  → Remember its shape, textures, details\n"
    "  → Ignore its background\n\n"
    "STEP 3 - FIND LOCATION:\n"
    "  → IMAGE 2 (mask) shows colored area = exact spot\n"
    "  → IMAGE 1 shows sketch = rough guide (erase it!)\n\n"
    "STEP 4 - PLACE OBJECT:\n"
    "  → Put object in colored area (from IMAGE OTHER)\n"
    "  → Follow user's prompt (orientation, pose, etc.)\n"
    "  → ERASE sketch completely\n\n"
    "STEP 5 - MAKE IT REALISTIC:\n"
    "  → Relight object to match IMAGE 1's lighting\n"
    "  → Adjust colors to match scene\n"
    "  → Cast shadows (direction must match scene)\n"
    "  → Blend edges smoothly\n\n"
    "MORE EXAMPLES:\n"
    "Example 1 - 'Поставь этот стул в углу у окна':\n"
    "  → Find chair in IMAGE OTHER\n"
    "  → Place it in corner near window (colored area from IMAGE 1)\n"
    "  → Erase colored sketch\n"
    "  → Relight with window light\n"
    "  → Cast shadow\n"
    "  → DONE!\n\n"
    "Example 2 - 'Add this person sitting at the desk':\n"
    "  → Find person in IMAGE OTHER\n"
    "  → Place at desk (colored area)\n"
    "  → Make them SITTING (user said so!)\n"
    "  → Erase sketch\n"
    "  → Relight with office lights\n"
    "  → DONE!\n\n"
    "Example 3 - 'добавь мужчину на траве в обведённом кругу':\n"
    "  → Find man in IMAGE OTHER\n"
    "  → Place ON GRASS in circle area (IMAGE 1)\n"
    "  → Erase circle sketch\n"
    "  → Relight with outdoor lighting\n"
    "  → Cast shadow on grass\n"
    "  → DONE!\n\n"
    "WHAT YOU MUST DO:\n"
    "✅ Follow user's prompt EXACTLY\n"
    "✅ Place object in colored area (IMAGE 2)\n"
    "✅ ERASE sketch completely\n"
    "✅ Relight object to match scene\n"
    "✅ Cast shadows\n"
    "✅ Make it look photorealistic\n\n"
    "WHAT YOU MUST NOT DO:\n"
    "❌ NEVER ignore user's prompt\n"
    "❌ NEVER place object in wrong spot\n"
    "❌ NEVER keep sketch visible\n"
    "❌ NEVER forget shadows\n\n"
    "FINAL REMINDER:\n"
    "🔴 USER PROMPT (at top) = YOUR PRIMARY INSTRUCTION!\n"
    "🔴 Read it carefully and do EXACTLY what it says!\n"
)

# 编辑-使用遮罩
EDIT_WITH_MASK = (
    "INPAINTING TASK - Replace sketch with photorealistic content:\n\n"

    "CONTEXT:\n"
    "User drew a rough SKETCH on their image to show where they want NEW content.\n"
    "The sketch is UGLY and TEMPORARY - it's just a guide.\n"
    "Your job: ERASE the sketch, CREATE beautiful realistic content in that spot.\n\n"

    "IMAGE 1 (PHOTO WITH SKETCH OVERLAY):\n"
    "- Original photo/render with user's sketch drawn on top\n"
    "- Sketch colors show LOCATION and rough SHAPE only\n"
    "- Sketch is NOT the final look - it will be DELETED\n\n"

    "IMAGE 2 (MASK - WHERE TO EDIT):\n"
    "- Black areas = DON'T TOUCH (keep original)\n"
    "- Colored areas = SKETCH LOCATION (delete sketch, add new content)\n\n"

    "STEP-BY-STEP PROCESS:\n"
    "1. Look at IMAGE 1 - see the ugly sketch user drew\n"
    "2. Look at IMAGE 2 - see WHERE the sketch is\n"
    "3. Read user's PROMPT - understand WHAT to create\n"
    "4. COMPLETELY ERASE the sketch from those areas\n"
    "5. CREATE photorealistic content matching the prompt\n"
    "6. Match original image's lighting, shadows, perspective, style\n"
    "7. Blend edges perfectly (no visible seams)\n\n"

    "REAL EXAMPLES:\n"
    "Example 1:\n"
    "  - User draws RED CIRCLE\n"
    "  - Prompt: 'add sunset light through window'\n"
    "  - You do: DELETE red circle → CREATE realistic warm sunlight rays\n"
    "  - Final: Beautiful sunset light, NO red circle visible\n\n"

    "Example 2:\n"
    "  - User draws BLUE BLOB\n"
    "  - Prompt: 'add water puddle on floor'\n"
    "  - You do: DELETE blue blob → CREATE realistic water with reflections\n"
    "  - Final: Real water puddle, NO blue blob visible\n\n"

    "Example 3:\n"
    "  - User draws GREEN SCRIBBLES\n"
    "  - Prompt: 'add plant in vase'\n"
    "  - You do: DELETE green scribbles → CREATE detailed plant with leaves\n"
    "  - Final: Beautiful plant, NO scribbles visible\n\n"

    "CRITICAL RULES:\n"
    "❌ NEVER keep the sketch visible\n"
    "❌ NEVER 'improve' the sketch - DELETE it completely\n"
    "❌ NEVER leave construction lines, rough shapes, or color blobs\n"
    "✅ ALWAYS erase sketch 100% before creating new content\n"
    "✅ ALWAYS create photorealistic result\n"
    "✅ ALWAYS match original image lighting and style\n"
    "✅ ALWAYS blend seamlessly at edges\n"
    "✅ ALWAYS follow user's text prompt for WHAT to create\n\n"

    "REMEMBER:\n"
    "Sketch = temporary guide (like construction lines in drawing)\n"
    "Final image = professional result with NO sketch traces\n"
    "User drew sketch to show LOCATION + rough IDEA\n"
    "You create PHOTOREALISTIC version and REMOVE sketch completely\n"
)
# 编辑-使用参考
EDIT_WITH_REFERENCES = (
    "PHOTOREALISTIC OBJECT INTEGRATION - Seamlessly blend reference into scene:\n\n"
    "CRITICAL CONTEXT:\n"
    "User is NOT asking for simple copy-paste! They want PHOTOREALISTIC INTEGRATION.\n"
    "The object from reference must look like it was PHOTOGRAPHED in the target scene.\n"
    "This requires ADVANCED color grading, lighting match, shadow casting, and perspective correction.\n\n"
    "IMAGE 1 (TARGET SCENE - DESTINATION):\n"
    "- This is your PRIMARY reference for visual style\n"
    "- Analyze: lighting direction, color temperature, shadow hardness, ambient light\n"
    "- The object from IMAGE 1 must MATCH this scene's lighting 100%\n\n"
    "IMAGE OTHER (REFERENCE - SOURCE OBJECT):\n"
    "- Contains the object/person to integrate into IMAGE 1\n"
    "- Extract its SHAPE and STRUCTURE (what it is)\n"
    "- IGNORE its original lighting, colors, and background\n"
    "- Think: 'I need this OBJECT, but I'll RELIGHT it for the new scene'\n\n"
    "YOUR TASK - PROFESSIONAL COMPOSITING:\n"
    "STEP 1 - LIGHTING ANALYSIS (IMAGE 1):\n"
    "- Light direction: Where are shadows pointing? (e.g., left side, top-right)\n"
    "- Light hardness: Sharp shadows = hard light, soft shadows = diffuse light\n"
    "- Color temperature: Warm (orange/yellow) or cool (blue/white)?\n"
    "- Ambient light: How bright are shadow areas?\n"
    "- Reflections: Are there glossy surfaces? What do they reflect?\n\n"
    "STEP 2 - OBJECT EXTRACTION (IMAGE OTHER):\n"
    "- Identify the object shape, structure, materials\n"
    "- Forget its current lighting - you will RELIGHT it\n"
    "- Preserve textures and material properties (metal, wood, fabric, etc.)\n\n"
    "STEP 3 - INTEGRATION (CRITICAL!):\n"
    "A. RELIGHTING:\n"
    "   - Apply IMAGE 1's light direction to the object\n"
    "   - Match light color temperature exactly\n"
    "   - Create shadows that match IMAGE 1's shadow style\n"
    "   - Add ambient occlusion in contact areas\n"
    "B. COLOR GRADING:\n"
    "   - Adjust object's colors to match IMAGE 1's color palette\n"
    "   - If IMAGE 1 is warm → warm the object's colors\n"
    "   - If IMAGE 1 is desaturated → reduce object's saturation\n"
    "   - Match overall brightness/exposure\n"
    "C. SHADOWS:\n"
    "   - Cast shadows from object onto IMAGE 1's surfaces\n"
    "   - Shadow direction MUST match IMAGE 1's existing shadows\n"
    "   - Shadow softness MUST match IMAGE 1's shadow hardness\n"
    "   - Add contact shadows (dark areas where object touches surface)\n"
    "D. PERSPECTIVE:\n"
    "   - Match camera angle from IMAGE 1\n"
    "   - Scale object appropriately for scene\n"
    "   - Ensure ground plane alignment\n"
    "E. REFLECTIONS & AMBIENT:\n"
    "   - If object is glossy → reflect IMAGE 1's environment\n"
    "   - Add ambient light bounce from IMAGE 1's surfaces\n"
    "   - Color spill: nearby colored surfaces affect object colors\n\n"
    "STEP 4 - FINAL BLEND:\n"
    "- Edge softness: match IMAGE 1's sharpness/blur\n"
    "- Atmospheric perspective: distant objects are hazier\n"
    "- Depth of field: match IMAGE 1's focus plane\n"
    "- Film grain/noise: match IMAGE 1's texture\n\n"
    "REAL-WORLD EXAMPLE:\n"
    "IMAGE 1: Dark moody interior with warm tungsten lights from left\n"
    "IMAGE 2: Photo of a red chair (photographed outdoors, bright daylight)\n"
    "USER: 'Add the chair by the window'\n"
    "WRONG (copy-paste): Bright red chair with daylight look = looks fake!\n"
    "RIGHT (professional integration):\n"
    "  → Chair shape preserved\n"
    "  → BUT relit with warm tungsten light from left\n"
    "  → Red color adjusted to warm/darker tone matching room\n"
    "  → Soft shadow cast to the right (opposite of light)\n"
    "  → Contact shadow under chair legs (ambient occlusion)\n"
    "  → Slight warm color spill from wooden floor onto chair base\n"
    "  → Chair looks like it was PHOTOGRAPHED in this room\n\n"
    "CRITICAL SUCCESS CRITERIA:\n"
    "✅ Object MUST look like it was PHOTOGRAPHED in IMAGE 1's scene\n"
    "✅ Lighting on object MUST match IMAGE 1 exactly (direction, color, hardness)\n"
    "✅ Object colors MUST be color-graded to match IMAGE 1's palette\n"
    "✅ Shadows MUST be cast correctly with right direction and softness\n"
    "✅ No visible compositing edges - perfect blend\n"
    "✅ Viewer should NOT be able to tell it's from different photo\n"
    "CRITICAL MISTAKES TO AVOID:\n"
    "❌ NEVER keep object's original lighting from IMAGE OTHER\n"
    "❌ NEVER keep object's original colors unchanged\n"
    "❌ NEVER forget to cast shadows onto IMAGE 1's surfaces\n"
    "❌ NEVER ignore IMAGE 1's light direction\n"
    "❌ NEVER make it look like a PNG sticker pasted on\n"
    "❌ NEVER create lighting conflicts (e.g., shadows wrong direction)\n\n"
    "REMEMBER:\n"
    "You are a PROFESSIONAL COMPOSITOR, not a copy-paste tool.\n"
    "The object must be RELIT, COLOR-GRADED, and SHADOWED to match the target scene.\n"
    "Final result should be INDISTINGUISHABLE from a real photograph.\n"
    "OLD STYLE TRANSFER PROMPT (for reference, DON'T use this):\n"
    "You are receiving TWO images:\n\n"
    "IMAGE 1 (Original Image - ONLY for composition):\n"
    "- Use EXCLUSIVELY for object positions, layout, scene structure\n"
    "- IGNORE its colors, materials, lighting, and current style\n"
    "- Treat current look as TEMPORARY - will be completely replaced\n"
    "- Keep ONLY the composition, everything else changes\n\n"
    "IMAGE OTHER (Style Reference - YOUR PRIMARY GUIDE):\n"
    "- This is your MAIN reference for ALL visual aspects\n"
    "- COPY AGGRESSIVELY: lighting setup, material types, color palette, texture quality, mood, atmosphere\n"
    "- Study this image's visual language and REPLICATE it completely\n"
    "- This shows the TARGET result you must achieve\n\n"
    "YOUR TASK - AGGRESSIVE STYLE TRANSFORMATION:\n"
    "1. Keep ONLY composition/layout/objects from IMAGE 1\n"
    "2. COMPLETELY REPLACE materials with IMAGE OTHER style:\n"
    "   - If IMAGE OTHER has metallic materials → make IMAGE 1's objects metallic\n"
    "   - If IMAGE OTHER has matte surfaces → make IMAGE 1's objects matte\n"
    "   - If IMAGE OTHER has wood texture → apply wood-like materials\n"
    "3. COMPLETELY REPLACE lighting with IMAGE OTHER setup:\n"
    "   - Match light direction, intensity, color temperature\n"
    "   - Copy shadow hardness/softness\n"
    "   - Replicate ambient lighting mood\n"
    "4. COMPLETELY REPLACE colors with IMAGE OTHER palette:\n"
    "   - If IMAGE OTHER is warm (orange/red) → make IMAGE 1 warm\n"
    "   - If IMAGE OTHER is cool (blue/cyan) → make IMAGE 1 cool\n"
    "   - Match color saturation and vibrancy\n"
    "5. REPLICATE atmosphere and mood:\n"
    "   - If IMAGE OTHER is dramatic → make IMAGE 1 dramatic\n"
    "   - If IMAGE OTHER is soft/gentle → make IMAGE 1 soft/gentle\n"
    "   - Copy depth, detail level, visual complexity\n\n"
    "CRITICAL - BE AGGRESSIVE, NOT CONSERVATIVE:\n"
    "❌ DON'T just 'slightly adjust' IMAGE 1\n"
    "❌ DON'T preserve IMAGE 1's current colors/materials\n"
    "❌ DON'T be subtle or gentle with changes\n"
    "✅ COMPLETELY TRANSFORM to match IMAGE OTHER style\n"
    "✅ Think: 'IMAGE OTHER is the goal, IMAGE 1 is just a layout template'\n"
    "✅ If IMAGE OTHER is blue but IMAGE 1 is red → make it BLUE\n"
    "✅ If IMAGE OTHER is dark but IMAGE 1 is bright → make it DARK\n"
    "✅ If IMAGE OTHER is detailed but IMAGE 1 is simple → add DETAILS\n\n"
    "EXAMPLE:\n"
    "- IMAGE 1: Cool blue render with flat lighting\n"
    "- IMAGE OTHER: Warm sunset photo with golden light, soft shadows, rich textures\n"
    "- YOUR RESULT: Keep IMAGE 1's objects/layout BUT with:\n"
    "  → Golden sunset lighting from IMAGE OTHER\n"
    "  → Warm orange/red colors from IMAGE OTHER\n"
    "  → Soft shadows and rich textures from IMAGE OTHER\n"
    "  → Final looks like IMAGE OTHER style applied to IMAGE 1's composition\n\n"
    "REMEMBER:\n"
    "Original image (IMAGE 1) = composition template ONLY\n"
    "Style reference (IMAGE OTHER) = your visual TARGET\n"
    "AGGRESSIVELY copy IMAGE OTHER visual style to IMAGE 1's layout\n"
)

# 没有遮罩也没有参考图片,只有提示词输入的基本提示词
EDIT_BASE_PROMPT = (
    "You are REFINING and IMPROVING an existing image:\n\n"
    "ORIGINAL IMAGE:\n"
    "- This is the base image you'll improve\n"
    "- Keep main composition, subjects, layout\n\n"
    "YOUR TASK:\n"
    "1. Understand current image\n"
    "2. Apply user's improvement instructions\n"
    "3. Keep overall composition intact\n"
    "4. Make changes feel natural and cohesive\n"
    "5. Enhance quality while preserving intent\n"
)
